"""
This type stub file was generated by pyright.
"""

import urllib.request

ACCEPT_HEADER = ...

class _FeedURLHandler(
    urllib.request.HTTPDigestAuthHandler,
    urllib.request.HTTPRedirectHandler,
    urllib.request.HTTPDefaultErrorHandler,
):
    def http_error_default(self, req, fp, code, msg, headers): ...
    
    def http_error_301(
        self, req, fp, code, msg, headers
    ) -> urllib.request.AddBaseHandler | None: ...
    
    http_error_300 = ...
    http_error_302 = ...
    http_error_303 = ...
    http_error_307 = ...
    
    def http_error_401(
        self, req, fp, code, msg, headers
    ) -> urllib.request.AddBaseHandler | None: ...


def get(
    url,
    etag=...,
    modified=...,
    agent=...,
    referrer=...,
    handlers=...,
    request_headers=...,
    result=...,
): ...
