"""
This type stub file was generated by pyright.
"""

from time import struct_time

_hungarian_months = ...
_hungarian_date_format_re = ...

def _parse_date_hungarian(date_string: str) -> struct_time: ...
